title: Stackbit Exto Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
color_scheme: light
accent_color: pink
header:
  title: Exto
  has_nav: true
  nav_links:
    - label: About
      url: /about/
      style: link
    - label: Portfolio
      url: /portfolio/
      style: link
    - label: Contact
      url: /contact/
      style: link
    - label: LinkedIn
      url: '#'
      style: icon
      icon: linkedin
      new_window: true
      no_follow: false
      type: action
footer:
  content: '&copy; 2021 Kimberly Pellikan'
  has_social: false
  social_links:
    - label: Instagram
      url: 'https://www.instagram.com/'
      style: icon
      icon: instagram
      new_window: true
    - label: Dribbble
      url: 'https://dribbble.com/'
      style: icon
      icon: dribbble
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon: linkedin
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://kpportfolio-fb961.netlify.app'
